services:
  web:
    build: . # builds only if there is no image
    ports:
      - "5000:5000"
    environment:
      - "MY_NAME=Student"

  database:
    image: postgres:15.11-alpine3.21
    environment:
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - ./data:/var/lib/postgresql/data


# add docker-compose up --build